import os
from pathlib import Path
from typing import Iterator, Tuple
import pathspec

EXTENSION_MAP = {
    ".py":   "python",
    # ".ts":   "typescript",
    # ".tsx":  "typescript",
    # ".js":   "javascript",
    # ".go":   "go",
    # ".java": "java",
    # ".rs":   "rust",
    # ".cpp":  "cpp",
    # ".c":    "c",
}

IGNORED_DIRS = {
    "node_modules", ".git", "venv", "__pycache__", "dist", "build", ".tox", ".venv", ".env", "__init__", "tests"
}

def is_binary(file_path: Path) -> bool:
    try:
        with file_path.open('tr') as check_file:  # try opening as text
            check_file.read(1024)
            return False
    except UnicodeDecodeError:
        return True
    except Exception:
        return True # Default to skip if we can't read it

def is_auto_generated(file_path: Path) -> bool:
    try:
        with file_path.open('r', encoding='utf-8', errors='ignore') as f:
            for _ in range(5):
                line = f.readline()
                if not line:
                    break
                line_lower = line.lower()
                if any(marker in line_lower for marker in [
                    "do not edit", "generated by", "@generated", "auto-generated"
                ]):
                    return True
    except Exception:
        pass
    return False

def walk_repo(repo_root: str) -> Iterator[Tuple[str, str]]:
    root_path = Path(repo_root).resolve()
    
    # Load .gitignore if present
    gitignore_path = root_path / ".gitignore"
    spec = None
    if gitignore_path.exists():
        with gitignore_path.open('r') as f:
            spec = pathspec.PathSpec.from_lines('gitignore', f)
            
    # Efficient traversal that prunes ignored directories
    stack = [root_path]
    
    while stack:
        current_dir = stack.pop()
        
        try:
            for item in current_dir.iterdir():
                # Make sure we don't error out on broken symlinks or similar weirdness
                if not item.exists():
                    continue

                rel_path = item.relative_to(root_path)
                
                # Check .gitignore
                # Important: pathspec matching for directories is better with a trailing slash
                is_dir = item.is_dir()
                match_path = f"{rel_path}/" if is_dir else str(rel_path)
                
                if spec and spec.match_file(match_path):
                    continue
                    
                if is_dir:
                    if item.name not in IGNORED_DIRS:
                        stack.append(item)
                elif item.is_file():
                    ext = item.suffix
                    if ext not in EXTENSION_MAP:
                        continue
                        
                    if is_binary(item):
                        continue
                        
                    if is_auto_generated(item):
                        continue
                        
                    yield str(rel_path), EXTENSION_MAP[ext]
        except PermissionError:
            continue
