import os
import shutil
from pathlib import Path
from ingestion.walker import walk_repo, is_binary, is_auto_generated

def test_walker_filtering(tmp_path):
    # Setup test directory structure
    repo_root = tmp_path / "test_repo"
    repo_root.mkdir()
    
    # .gitignore
    (repo_root / ".gitignore").write_text("*.tmp\nignored_dir/\n")
    
    # Valid files
    src_dir = repo_root / "src"
    src_dir.mkdir()
    (src_dir / "main.py").write_text("print('hello')\n")
    (src_dir / "utils.ts").write_text("export const a = 1;\n")
    
    # Ignored by default dirs
    node_modules = repo_root / "node_modules"
    node_modules.mkdir()
    (node_modules / "bad.py").write_text("bad")
    
    # Ignored by .gitignore
    (repo_root / "test.tmp").write_text("tmp")
    ignored_dir = repo_root / "ignored_dir"
    ignored_dir.mkdir()
    (ignored_dir / "ignored.py").write_text("ignored")
    
    # Binary file
    bin_file = src_dir / "binary.py"
    with bin_file.open('wb') as f:
        f.write(b'\x00\x01\x02\x03\x04\xff')
        
    # Auto-generated file
    gen_file = src_dir / "generated.py"
    gen_file.write_text("# DO NOT EDIT\n# Auto-generated file\nprint('gen')\n")
    
    # Unsupported extension
    (src_dir / "doc.txt").write_text("hello doc")
    
    # Run walker
    results = list(walk_repo(str(repo_root)))
    
    # Convert results to a set of (path_string, lang)
    normalized_results = {(Path(p).as_posix(), lang) for p, lang in results}
    
    expected = {
        ("src/main.py", "python"),
        ("src/utils.ts", "typescript"),
    }
    
    assert normalized_results == expected

def test_is_auto_generated(tmp_path):
    file1 = tmp_path / "f1.py"
    file1.write_text("# @generated by tool\n")
    assert is_auto_generated(file1) is True
    
    file2 = tmp_path / "f2.py"
    file2.write_text("def hello():\n    pass\n")
    assert is_auto_generated(file2) is False

def test_is_binary(tmp_path):
    bin_file = tmp_path / "test.bin"
    with bin_file.open("wb") as f:
        f.write(b'\xff\xfe\x00\x00')
    assert is_binary(bin_file) is True
    
    txt_file = tmp_path / "test.txt"
    txt_file.write_text("hello world")
    assert is_binary(txt_file) is False
